version: "3"

services:
  web:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverVersion=${MYSQL_SERVER_VERSION}"

  db:
    image: "mysql:${MYSQL_SERVER_VERSION}"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"
    volumes:
      - dbvolume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD

volumes:
  dbvolume: