version: "3"

services:

  web:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverVersion=${MYSQL_SERVER_VERSION}"

  db:
    image: "mysql:${MYSQL_SERVER_VERSION}"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD