version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./app:$APP_ROOT
      - ./docker/web/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./app:$APP_ROOT
    networks:
      - code-network
    environment:
      KEYS_PASSPHRASE: $KEYS_PASSPHRASE
      APP_ROOT: $APP_ROOT
      MAILER_DSN: $MAILER_DSN
      APP_DOMAIN: $APP_DOMAIN
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverVersion=${MYSQL_SERVER_VERSION}"

  db:
    image: "mysql:${MYSQL_SERVER_VERSION}"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"
    volumes:
      - dbvolume:/var/lib/mysql
    networks:
      - code-network
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD

volumes:
  dbvolume:

networks:
  code-network:
    driver: bridge